CREATE TABLE IF NOT EXISTS `scheduled_notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `channel` enum('EMAIL','WHATSAPP') NOT NULL,
  `notification_type` varchar(100) NOT NULL DEFAULT 'TASK_REMINDER',
  `message` text DEFAULT NULL,
  `scheduled_at` datetime NOT NULL,
  `status` enum('PENDING','PROCESSING','SENT','FAILED','CANCELLED') NOT NULL DEFAULT 'PENDING',
  `attempts` int(11) NOT NULL DEFAULT 0,
  `sent_at` datetime DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_scheduled_notifications_scheduled_at` (`scheduled_at`),
  KEY `idx_scheduled_notifications_status` (`status`),
  KEY `idx_scheduled_notifications_task` (`task_id`),
  KEY `idx_scheduled_notifications_user` (`user_id`),
  KEY `idx_scheduled_notifications_due` (`status`,`scheduled_at`),
  CONSTRAINT `fk_scheduled_notifications_task` FOREIGN KEY (`task_id`) REFERENCES `tasks` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scheduled_notifications_user` FOREIGN KEY (`user_id`) REFERENCES `admin` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_scheduled_notifications_created_by` FOREIGN KEY (`created_by`) REFERENCES `admin` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
